version: '1.0'
stages:
  - build
  - test
steps:
  buildtesttarget:
    title: Building Environment to run AUT
    type: build
    stage: build
    tag: v1.0.0
    cmd: .\build.ps1
  installpackages:
    title: Install Packages
    type: build
    stage: build
    tag: v1.0.0
    cmd: .\install.ps1
  executetest:
    title: Execute Tests
    type: test
    stage: test
    tag: v1.0.0
    cmd: .\test.ps1
